---
# Source: longbow/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: longbow
  labels:
    helm.sh/chart: longbow-0.0.4
    app.kubernetes.io/name: longbow
    app.kubernetes.io/instance: longbow
    app.kubernetes.io/version: "0.0.8"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken:
---
# Source: longbow/templates/service-data.yaml
apiVersion: v1
kind: Service
metadata:
  name: longbow-data
  labels:
    helm.sh/chart: longbow-0.0.4
    app.kubernetes.io/name: longbow
    app.kubernetes.io/instance: longbow
    app.kubernetes.io/version: "0.0.8"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: grpc-data
      protocol: TCP
      name: grpc-data
  selector:
    app.kubernetes.io/name: longbow
    app.kubernetes.io/instance: longbow
---
# Source: longbow/templates/service-meta.yaml
apiVersion: v1
kind: Service
metadata:
  name: longbow-meta
  labels:
    helm.sh/chart: longbow-0.0.4
    app.kubernetes.io/name: longbow
    app.kubernetes.io/instance: longbow
    app.kubernetes.io/version: "0.0.8"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: grpc-meta
      protocol: TCP
      name: grpc-meta
  selector:
    app.kubernetes.io/name: longbow
    app.kubernetes.io/instance: longbow
---
# Source: longbow/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: longbow
  labels:
    helm.sh/chart: longbow-0.0.4
    app.kubernetes.io/name: longbow
    app.kubernetes.io/instance: longbow
    app.kubernetes.io/version: "0.0.8"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: longbow
      app.kubernetes.io/instance: longbow
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9090"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: longbow
        app.kubernetes.io/instance: longbow
    spec:
      serviceAccountName: longbow
      securityContext:
        fsGroup: 2000
      containers:
        - name: longbow
          securityContext:
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "ghcr.io/23skdu/longbow:0.0.8"
          imagePullPolicy: IfNotPresent
          env:
            - name: LONGBOW_LISTEN_ADDR
              value: "0.0.0.0:3000"
            - name: LONGBOW_META_ADDR
              value: "0.0.0.0:3001"
            - name: LONGBOW_METRICS_ADDR
              value: "0.0.0.0:9090"
            - name: LONGBOW_DATA_PATH
              value: "/data"
            - name: LONGBOW_SNAPSHOT_PATH
              value: "/snapshots"
            - name: LONGBOW_MAX_MEMORY
              value: "1073741824"
            - name: LONGBOW_MAX_WAL_SIZE
              value: "104857600"
            - name: LONGBOW_SNAPSHOT_INTERVAL
              value: "1h"
            - name: LONGBOW_TTL
              value: "0s"
            # gRPC Options
            - name: LONGBOW_GRPC_MAX_RECV_MSG_SIZE
              value: "6.7108864e+07"
            - name: LONGBOW_GRPC_MAX_SEND_MSG_SIZE
              value: "6.7108864e+07"
            - name: LONGBOW_GRPC_INITIAL_WINDOW_SIZE
              value: "1.048576e+06"
            - name: LONGBOW_GRPC_INITIAL_CONN_WINDOW_SIZE
              value: "1.048576e+06"
            - name: LONGBOW_GRPC_MAX_CONCURRENT_STREAMS
              value: "250"
            - name: LONGBOW_GRPC_KEEPALIVE_TIME
              value: "2h"
            - name: LONGBOW_GRPC_KEEPALIVE_TIMEOUT
              value: "20s"
            - name: LONGBOW_GRPC_KEEPALIVE_MIN_TIME
              value: "5m"
            - name: LONGBOW_GRPC_KEEPALIVE_PERMIT_WITHOUT_STREAM
              value: "false"
            # Gossip Configuration
            - name: GOSSIP_ENABLED
              value: "true"
            - name: GOSSIP_PORT
              value: "7946"
            - name: GOSSIP_INTERVAL
              value: 
            # Storage Configuration
            - name: STORAGE_ASYNC_FSYNC
              value: "true"
            - name: STORAGE_DOPUT_BATCH_SIZE
              value: "100"

          ports:
            - name: grpc-data
              containerPort: 3000
              protocol: TCP
            - name: grpc-meta
              containerPort: 3001
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: grpc-data
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: grpc-data
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {}
          volumeMounts:
      volumes:
---
# Source: longbow/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "longbow-test-connection"
  labels:
    helm.sh/chart: longbow-0.0.4
    app.kubernetes.io/name: longbow
    app.kubernetes.io/instance: longbow
    app.kubernetes.io/version: "0.0.8"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['longbow:']
  restartPolicy: Never
