// Code generated by command: go run all_kernels_gen.go -out internal/simd/all_kernels_avo_amd64.s -stubs internal/simd/all_kernels_stubs_amd64.go -pkg simd. DO NOT EDIT.

#include "textflag.h"

// func euclidean8AVX2(a uintptr, b uintptr) float32
// Requires: AVX, SSE
TEXT ·euclidean8AVX2(SB), NOSPLIT, $0-20
	MOVQ         a+0(FP), AX
	MOVQ         b+8(FP), CX
	VMOVUPS      (AX), Y0
	VMOVUPS      (CX), Y1
	VSUBPS       Y1, Y0, Y0
	VMULPS       Y0, Y0, Y0
	VEXTRACTF128 $0x00, Y0, X1
	VEXTRACTF128 $0x01, Y0, X0
	VADDPS       X1, X0, X0
	VMOVHLPS     X0, X2, X2
	VADDPS       X2, X0, X0
	VMOVSHDUP    X0, X1
	VADDSS       X1, X0, X0
	MOVSS        X0, ret+16(FP)
	VZEROUPPER
	RET

// func dot8AVX2(a uintptr, b uintptr) float32
// Requires: AVX, SSE
TEXT ·dot8AVX2(SB), NOSPLIT, $0-20
	MOVQ         a+0(FP), AX
	MOVQ         b+8(FP), CX
	VMOVUPS      (AX), Y0
	VMOVUPS      (CX), Y1
	VMULPS       Y0, Y1, Y0
	VEXTRACTF128 $0x00, Y0, X1
	VEXTRACTF128 $0x01, Y0, X0
	VADDPS       X1, X0, X0
	VMOVHLPS     X0, X2, X2
	VADDPS       X2, X0, X0
	VMOVSHDUP    X0, X1
	VADDSS       X1, X0, X0
	MOVSS        X0, ret+16(FP)
	VZEROUPPER
	RET

// func euclidean16AVX512(a uintptr, b uintptr) float32
// Requires: AVX, AVX512F, SSE
TEXT ·euclidean16AVX512(SB), NOSPLIT, $0-20
	MOVQ          a+0(FP), AX
	MOVQ          b+8(FP), CX
	VMOVUPS       (AX), Z0
	VMOVUPS       (CX), Z1
	VSUBPS        Z1, Z0, Z0
	VMULPS        Z0, Z0, Z0
	VEXTRACTF64X4 $0x00, Z0, Y1
	VEXTRACTF64X4 $0x01, Z0, Y0
	VADDPS        Y1, Y0, Y0
	VEXTRACTF128  $0x00, Y0, X1
	VEXTRACTF128  $0x01, Y0, X0
	VADDPS        X1, X0, X0
	VMOVHLPS      X0, X2, X2
	VADDPS        X2, X0, X0
	VMOVSHDUP     X0, X1
	VADDSS        X1, X0, X0
	MOVSS         X0, ret+16(FP)
	VZEROUPPER
	RET

// func dot16AVX512(a uintptr, b uintptr) float32
// Requires: AVX, AVX512DQ, AVX512F, SSE
TEXT ·dot16AVX512(SB), NOSPLIT, $0-20
	MOVQ          a+0(FP), AX
	MOVQ          b+8(FP), CX
	VXORPS        Z0, Z0, Z0
	VMOVUPS       (AX), Z1
	VMOVUPS       (CX), Z2
	VFMADD231PS   Z1, Z2, Z0
	VEXTRACTF64X4 $0x00, Z0, Y1
	VEXTRACTF64X4 $0x01, Z0, Y0
	VADDPS        Y1, Y0, Y0
	VEXTRACTF128  $0x00, Y0, X1
	VEXTRACTF128  $0x01, Y0, X0
	VADDPS        X1, X0, X0
	VMOVHLPS      X0, X3, X3
	VADDPS        X3, X0, X0
	VMOVSHDUP     X0, X1
	VADDSS        X1, X0, X0
	MOVSS         X0, ret+16(FP)
	VZEROUPPER
	RET

// func prefetchNTA(p uintptr)
// Requires: MMX+
TEXT ·prefetchNTA(SB), NOSPLIT, $0-8
	MOVQ        p+0(FP), AX
	PREFETCHNTA (AX)
	RET

DATA neg_inf_const_red<>+0(SB)/4, $0xff800000
GLOBL neg_inf_const_red<>(SB), RODATA|NOPTR, $4

DATA pos_inf_const_red<>+0(SB)/4, $0x7f800000
GLOBL pos_inf_const_red<>(SB), RODATA|NOPTR, $4

// func sumAVX2Kernel(src uintptr, n int) float32
// Requires: AVX, SSE
TEXT ·sumAVX2Kernel(SB), NOSPLIT, $0-20
	MOVQ   src+0(FP), AX
	MOVQ   n+8(FP), CX
	VXORPS Y0, Y0, Y0

sum_loop:
	CMPQ    CX, $0x08
	JL      sum_tail
	VMOVUPS (AX), Y1
	VADDPS  Y1, Y0, Y0
	ADDQ    $0x20, AX
	SUBQ    $0x08, CX
	JMP     sum_loop

sum_tail:
	VEXTRACTF128 $0x00, Y0, X1
	VEXTRACTF128 $0x01, Y0, X0
	VADDPS       X1, X0, X0
	VMOVHLPS     X0, X2, X2
	VADDPS       X2, X0, X0
	VMOVSHDUP    X0, X1
	VADDSS       X1, X0, X0
	MOVSS        X0, ret+16(FP)
	VZEROUPPER
	RET

// func maxAVX2Kernel(src uintptr, n int) float32
// Requires: AVX, SSE
TEXT ·maxAVX2Kernel(SB), NOSPLIT, $0-20
	MOVQ         src+0(FP), AX
	MOVQ         n+8(FP), CX
	VBROADCASTSS neg_inf_const_red<>+0(SB), Y0

max_loop:
	CMPQ    CX, $0x08
	JL      max_tail
	VMOVUPS (AX), Y1
	VMAXPS  Y1, Y0, Y0
	ADDQ    $0x20, AX
	SUBQ    $0x08, CX
	JMP     max_loop

max_tail:
	VEXTRACTF128 $0x00, Y0, X1
	VEXTRACTF128 $0x01, Y0, X0
	VMAXPS       X1, X0, X0
	VMOVSHDUP    X0, X1
	VMAXSS       X1, X0, X0
	VPERMILPS    $0x4e, X0, X1
	VMAXSS       X1, X0, X0
	MOVSS        X0, ret+16(FP)
	VZEROUPPER
	RET

// func minAVX2Kernel(src uintptr, n int) float32
// Requires: AVX, SSE
TEXT ·minAVX2Kernel(SB), NOSPLIT, $0-20
	MOVQ         src+0(FP), AX
	MOVQ         n+8(FP), CX
	VBROADCASTSS pos_inf_const_red<>+0(SB), Y0

min_loop:
	CMPQ    CX, $0x08
	JL      min_tail
	VMOVUPS (AX), Y1
	VMINPS  Y1, Y0, Y0
	ADDQ    $0x20, AX
	SUBQ    $0x08, CX
	JMP     min_loop

min_tail:
	VEXTRACTF128 $0x00, Y0, X1
	VEXTRACTF128 $0x01, Y0, X0
	VMINPS       X1, X0, X0
	VMOVSHDUP    X0, X1
	VMINSS       X1, X0, X0
	VPERMILPS    $0x4e, X0, X1
	VMINSS       X1, X0, X0
	MOVSS        X0, ret+16(FP)
	VZEROUPPER
	RET

// func l2SquaredAVX512Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·l2SquaredAVX512Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func dotAVX512Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·dotAVX512Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func euclideanFloat64AVX512Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·euclideanFloat64AVX512Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func dotFloat64AVX512Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·dotFloat64AVX512Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func euclideanF16AVX512Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·euclideanF16AVX512Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func dotF16AVX512Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·dotF16AVX512Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func euclideanF16AVX2Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·euclideanF16AVX2Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func dotF16AVX2Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·dotF16AVX2Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func dotInt4AVX512Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·dotInt4AVX512Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func dotInt4AVX2Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·dotInt4AVX2Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func euclideanFloat64AVX2Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·euclideanFloat64AVX2Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func euclideanInt8AVX2Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·euclideanInt8AVX2Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func euclideanInt16AVX2Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·euclideanInt16AVX2Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func euclideanUint16AVX2Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·euclideanUint16AVX2Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func dotInt16AVX2Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·dotInt16AVX2Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func dotUint16AVX2Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·dotUint16AVX2Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func euclideanInt8Unrolled4xAVX2Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·euclideanInt8Unrolled4xAVX2Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func dotFloat64AVX2Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·dotFloat64AVX2Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func brayCurtisAVX2Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·brayCurtisAVX2Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func manhattanAVX2Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·manhattanAVX2Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func chebyshevAVX2Kernel(a uintptr, b uintptr, n int) float32
// Requires: SSE
TEXT ·chebyshevAVX2Kernel(SB), NOSPLIT, $0-28
	MOVSS X0, ret+24(FP)
	RET

// func sigmoidAVX512Kernel(src uintptr, dst uintptr, n int)
TEXT ·sigmoidAVX512Kernel(SB), NOSPLIT, $0-24
	RET

// func expAVX512Kernel(src uintptr, dst uintptr, n int)
TEXT ·expAVX512Kernel(SB), NOSPLIT, $0-24
	RET

// func logAVX512Kernel(src uintptr, dst uintptr, n int)
TEXT ·logAVX512Kernel(SB), NOSPLIT, $0-24
	RET

// func int8ToFloat32AVX2Kernel(src uintptr, dst uintptr, n int)
TEXT ·int8ToFloat32AVX2Kernel(SB), NOSPLIT, $0-24
	RET

// func uint8ToFloat32AVX2Kernel(src uintptr, dst uintptr, n int)
TEXT ·uint8ToFloat32AVX2Kernel(SB), NOSPLIT, $0-24
	RET

// func int16ToFloat32AVX2Kernel(src uintptr, dst uintptr, n int)
TEXT ·int16ToFloat32AVX2Kernel(SB), NOSPLIT, $0-24
	RET

// func uint16ToFloat32AVX2Kernel(src uintptr, dst uintptr, n int)
TEXT ·uint16ToFloat32AVX2Kernel(SB), NOSPLIT, $0-24
	RET

// func int32ToFloat32AVX2Kernel(src uintptr, dst uintptr, n int)
TEXT ·int32ToFloat32AVX2Kernel(SB), NOSPLIT, $0-24
	RET

// func uint32ToFloat32AVX2Kernel(src uintptr, dst uintptr, n int)
TEXT ·uint32ToFloat32AVX2Kernel(SB), NOSPLIT, $0-24
	RET

// func float16ToFloat32AVX2Kernel(src uintptr, dst uintptr, n int)
TEXT ·float16ToFloat32AVX2Kernel(SB), NOSPLIT, $0-24
	RET

// func int8ToFloat32AVX512Kernel(src uintptr, dst uintptr, n int)
TEXT ·int8ToFloat32AVX512Kernel(SB), NOSPLIT, $0-24
	RET

// func uint8ToFloat32AVX512Kernel(src uintptr, dst uintptr, n int)
TEXT ·uint8ToFloat32AVX512Kernel(SB), NOSPLIT, $0-24
	RET

// func int16ToFloat32AVX512Kernel(src uintptr, dst uintptr, n int)
TEXT ·int16ToFloat32AVX512Kernel(SB), NOSPLIT, $0-24
	RET

// func uint16ToFloat32AVX512Kernel(src uintptr, dst uintptr, n int)
TEXT ·uint16ToFloat32AVX512Kernel(SB), NOSPLIT, $0-24
	RET

// func int32ToFloat32AVX512Kernel(src uintptr, dst uintptr, n int)
TEXT ·int32ToFloat32AVX512Kernel(SB), NOSPLIT, $0-24
	RET

// func uint32ToFloat32AVX512Kernel(src uintptr, dst uintptr, n int)
TEXT ·uint32ToFloat32AVX512Kernel(SB), NOSPLIT, $0-24
	RET

// func float16ToFloat32AVX512Kernel(src uintptr, dst uintptr, n int)
TEXT ·float16ToFloat32AVX512Kernel(SB), NOSPLIT, $0-24
	RET

// func softmaxAVX512Kernel(src uintptr, dst uintptr, n int)
TEXT ·softmaxAVX512Kernel(SB), NOSPLIT, $0-24
	RET

// func matchInt64AVX2Kernel(src uintptr, val int64, op int, dst uintptr, n int)
TEXT ·matchInt64AVX2Kernel(SB), NOSPLIT, $0-40
	RET

// func matchInt32AVX2Kernel(src uintptr, val int64, op int, dst uintptr, n int)
TEXT ·matchInt32AVX2Kernel(SB), NOSPLIT, $0-40
	RET

// func matchFloat32AVX2Kernel(src uintptr, val int64, op int, dst uintptr, n int)
TEXT ·matchFloat32AVX2Kernel(SB), NOSPLIT, $0-40
	RET

// func matchFloat64AVX2Kernel(src uintptr, val int64, op int, dst uintptr, n int)
TEXT ·matchFloat64AVX2Kernel(SB), NOSPLIT, $0-40
	RET

// func matchInt64AVX512Kernel(src uintptr, val int64, op int, dst uintptr, n int)
TEXT ·matchInt64AVX512Kernel(SB), NOSPLIT, $0-40
	RET

// func matchInt32AVX512Kernel(src uintptr, val int64, op int, dst uintptr, n int)
TEXT ·matchInt32AVX512Kernel(SB), NOSPLIT, $0-40
	RET

// func matchFloat32AVX512Kernel(src uintptr, val int64, op int, dst uintptr, n int)
TEXT ·matchFloat32AVX512Kernel(SB), NOSPLIT, $0-40
	RET

// func matchFloat64AVX512Kernel(src uintptr, val int64, op int, dst uintptr, n int)
TEXT ·matchFloat64AVX512Kernel(SB), NOSPLIT, $0-40
	RET

// func cosineDotAVX512(a uintptr, b uintptr, n int) (dot float32, normA float32, normB float32)
// Requires: SSE
TEXT ·cosineDotAVX512(SB), NOSPLIT, $0-36
	MOVSS X0, dot+24(FP)
	MOVSS X0, normA+28(FP)
	MOVSS X0, normB+32(FP)
	RET

// func euclideanVertical4AVX512(q uintptr, v0 uintptr, v1 uintptr, v2 uintptr, v3 uintptr, n int, res uintptr)
TEXT ·euclideanVertical4AVX512(SB), NOSPLIT, $0-56
	RET

// func cosineVertical4AVX512(q uintptr, v0 uintptr, v1 uintptr, v2 uintptr, v3 uintptr, n int, res uintptr)
TEXT ·cosineVertical4AVX512(SB), NOSPLIT, $0-56
	RET

// func dotVertical4AVX512(q uintptr, v0 uintptr, v1 uintptr, v2 uintptr, v3 uintptr, n int, res uintptr)
TEXT ·dotVertical4AVX512(SB), NOSPLIT, $0-56
	RET

// func euclideanVertical4AVX2(q uintptr, v0 uintptr, v1 uintptr, v2 uintptr, v3 uintptr, n int, res uintptr)
TEXT ·euclideanVertical4AVX2(SB), NOSPLIT, $0-56
	RET

// func dotVertical4AVX2(q uintptr, v0 uintptr, v1 uintptr, v2 uintptr, v3 uintptr, n int, res uintptr)
TEXT ·dotVertical4AVX2(SB), NOSPLIT, $0-56
	RET

// func cosineVertical4AVX2(q uintptr, v0 uintptr, v1 uintptr, v2 uintptr, v3 uintptr, n int, res uintptr)
TEXT ·cosineVertical4AVX2(SB), NOSPLIT, $0-56
	RET

// func euclideanSQ8AVX512Kernel(a uintptr, b uintptr, n int) int32
TEXT ·euclideanSQ8AVX512Kernel(SB), NOSPLIT, $0-28
	MOVL AX, ret+24(FP)
	RET

// func adcBatchAVX512Kernel(table uintptr, codes uintptr, m int, results uintptr, n int)
TEXT ·adcBatchAVX512Kernel(SB), NOSPLIT, $0-40
	RET

// func adcBatchVNNIKernel(table uintptr, codes uintptr, m int, results uintptr, n int)
TEXT ·adcBatchVNNIKernel(SB), NOSPLIT, $0-40
	RET

// func euclideanPQVNNIKernel(q uintptr, c uintptr, subDim int, k int, res uintptr)
TEXT ·euclideanPQVNNIKernel(SB), NOSPLIT, $0-40
	RET

// func adcBatchAVX2Kernel(table uintptr, codes uintptr, m int, results uintptr, n int)
TEXT ·adcBatchAVX2Kernel(SB), NOSPLIT, $0-40
	RET

// func euclideanSQ8AVX2Kernel(a uintptr, b uintptr, n int) int32
TEXT ·euclideanSQ8AVX2Kernel(SB), NOSPLIT, $0-28
	MOVL AX, ret+24(FP)
	RET

// func cosine8AVX2(a uintptr, b uintptr) (dot float32, normA float32, normB float32)
// Requires: SSE
TEXT ·cosine8AVX2(SB), NOSPLIT, $0-28
	MOVSS X0, dot+16(FP)
	MOVSS X0, normA+20(FP)
	MOVSS X0, normB+24(FP)
	RET

// func l2SquaredAVX2Kernel(a uintptr, b uintptr, n int, res uintptr)
TEXT ·l2SquaredAVX2Kernel(SB), NOSPLIT, $0-32
	RET

// func dotAVX2Kernel(a uintptr, b uintptr, n int, res uintptr)
TEXT ·dotAVX2Kernel(SB), NOSPLIT, $0-32
	RET

// func euclidean384AVX512Kernel(a uintptr, b uintptr) float32
// Requires: SSE
TEXT ·euclidean384AVX512Kernel(SB), NOSPLIT, $0-20
	MOVSS X0, ret+16(FP)
	RET

// func euclidean768AVX512Kernel(a uintptr, b uintptr) float32
// Requires: SSE
TEXT ·euclidean768AVX512Kernel(SB), NOSPLIT, $0-20
	MOVSS X0, ret+16(FP)
	RET

// func euclidean1536AVX512Kernel(a uintptr, b uintptr) float32
// Requires: SSE
TEXT ·euclidean1536AVX512Kernel(SB), NOSPLIT, $0-20
	MOVSS X0, ret+16(FP)
	RET

// func dot384AVX512Kernel(a uintptr, b uintptr) float32
// Requires: SSE
TEXT ·dot384AVX512Kernel(SB), NOSPLIT, $0-20
	MOVSS X0, ret+16(FP)
	RET

// func dot768AVX512Kernel(a uintptr, b uintptr) float32
// Requires: SSE
TEXT ·dot768AVX512Kernel(SB), NOSPLIT, $0-20
	MOVSS X0, ret+16(FP)
	RET

// func dot1536AVX512Kernel(a uintptr, b uintptr) float32
// Requires: SSE
TEXT ·dot1536AVX512Kernel(SB), NOSPLIT, $0-20
	MOVSS X0, ret+16(FP)
	RET

// func euclidean32FMA(a uintptr, b uintptr) float32
// Requires: SSE
TEXT ·euclidean32FMA(SB), NOSPLIT, $0-20
	MOVSS X0, ret+16(FP)
	RET

// func dot32FMA(a uintptr, b uintptr) float32
// Requires: SSE
TEXT ·dot32FMA(SB), NOSPLIT, $0-20
	MOVSS X0, ret+16(FP)
	RET

// func cosine32FMA(a uintptr, b uintptr) (dot float32, normA float32, normB float32)
// Requires: SSE
TEXT ·cosine32FMA(SB), NOSPLIT, $0-28
	MOVSS X0, dot+16(FP)
	MOVSS X0, normA+20(FP)
	MOVSS X0, normB+24(FP)
	RET

// func euclidean64FMA(a uintptr, b uintptr) float32
// Requires: SSE
TEXT ·euclidean64FMA(SB), NOSPLIT, $0-20
	MOVSS X0, ret+16(FP)
	RET

// func dot64FMA(a uintptr, b uintptr) float32
// Requires: SSE
TEXT ·dot64FMA(SB), NOSPLIT, $0-20
	MOVSS X0, ret+16(FP)
	RET

// func cosine64FMA(a uintptr, b uintptr) (dot float32, normA float32, normB float32)
// Requires: SSE
TEXT ·cosine64FMA(SB), NOSPLIT, $0-28
	MOVSS X0, dot+16(FP)
	MOVSS X0, normA+20(FP)
	MOVSS X0, normB+24(FP)
	RET

// func matMulAVX2(a uintptr, b uintptr, dst uintptr, m int, n int, k int)
TEXT ·matMulAVX2(SB), NOSPLIT, $0-48
	RET

// func argMaxAVX2Kernel(src uintptr, n int) (val float32, idx int)
// Requires: SSE
TEXT ·argMaxAVX2Kernel(SB), NOSPLIT, $0-32
	MOVSS X0, val+16(FP)
	MOVQ  AX, idx+24(FP)
	RET

// func argMinAVX2Kernel(src uintptr, n int) (val float32, idx int)
// Requires: SSE
TEXT ·argMinAVX2Kernel(SB), NOSPLIT, $0-32
	MOVSS X0, val+16(FP)
	MOVQ  AX, idx+24(FP)
	RET

// func argMaxAVX512Kernel(src uintptr, n int) (val float32, idx int)
// Requires: SSE
TEXT ·argMaxAVX512Kernel(SB), NOSPLIT, $0-32
	MOVSS X0, val+16(FP)
	MOVQ  AX, idx+24(FP)
	RET

// func argMinAVX512Kernel(src uintptr, n int) (val float32, idx int)
// Requires: SSE
TEXT ·argMinAVX512Kernel(SB), NOSPLIT, $0-32
	MOVSS X0, val+16(FP)
	MOVQ  AX, idx+24(FP)
	RET

// func expAVX2Kernel(src uintptr, dst uintptr, n int)
TEXT ·expAVX2Kernel(SB), NOSPLIT, $0-24
	RET

// func logAVX2Kernel(src uintptr, dst uintptr, n int)
TEXT ·logAVX2Kernel(SB), NOSPLIT, $0-24
	RET

// func softmaxAVX2Kernel(src uintptr, dst uintptr, n int)
TEXT ·softmaxAVX2Kernel(SB), NOSPLIT, $0-24
	RET

// func sigmoidAVX2Kernel(src uintptr, dst uintptr, n int)
TEXT ·sigmoidAVX2Kernel(SB), NOSPLIT, $0-24
	RET
