// Code generated by command: go run all_kernels_gen.go -out internal/simd/all_kernels_avo_amd64.s -stubs internal/simd/all_kernels_stubs_amd64.go -pkg simd. DO NOT EDIT.

package simd

func euclidean8AVX2(a uintptr, b uintptr) float32

func dot8AVX2(a uintptr, b uintptr) float32

func euclidean16AVX512(a uintptr, b uintptr) float32

func dot16AVX512(a uintptr, b uintptr) float32

func prefetchNTA(p uintptr)

func sumAVX2Kernel(src uintptr, n int) float32

func maxAVX2Kernel(src uintptr, n int) float32

func minAVX2Kernel(src uintptr, n int) float32

func l2SquaredAVX512Kernel(a uintptr, b uintptr, n int) float32

func dotAVX512Kernel(a uintptr, b uintptr, n int) float32

func euclideanFloat64AVX512Kernel(a uintptr, b uintptr, n int) float32

func dotFloat64AVX512Kernel(a uintptr, b uintptr, n int) float32

func euclideanF16AVX512Kernel(a uintptr, b uintptr, n int) float32

func dotF16AVX512Kernel(a uintptr, b uintptr, n int) float32

func euclideanF16AVX2Kernel(a uintptr, b uintptr, n int) float32

func dotF16AVX2Kernel(a uintptr, b uintptr, n int) float32

func dotInt4AVX512Kernel(a uintptr, b uintptr, n int) float32

func dotInt4AVX2Kernel(a uintptr, b uintptr, n int) float32

func euclideanFloat64AVX2Kernel(a uintptr, b uintptr, n int) float32

func euclideanInt8AVX2Kernel(a uintptr, b uintptr, n int) float32

func euclideanInt16AVX2Kernel(a uintptr, b uintptr, n int) float32

func euclideanUint16AVX2Kernel(a uintptr, b uintptr, n int) float32

func dotInt16AVX2Kernel(a uintptr, b uintptr, n int) float32

func dotUint16AVX2Kernel(a uintptr, b uintptr, n int) float32

func euclideanInt8Unrolled4xAVX2Kernel(a uintptr, b uintptr, n int) float32

func dotFloat64AVX2Kernel(a uintptr, b uintptr, n int) float32

func brayCurtisAVX2Kernel(a uintptr, b uintptr, n int) float32

func manhattanAVX2Kernel(a uintptr, b uintptr, n int) float32

func chebyshevAVX2Kernel(a uintptr, b uintptr, n int) float32

func sigmoidAVX512Kernel(src uintptr, dst uintptr, n int)

func expAVX512Kernel(src uintptr, dst uintptr, n int)

func logAVX512Kernel(src uintptr, dst uintptr, n int)

func int8ToFloat32AVX2Kernel(src uintptr, dst uintptr, n int)

func uint8ToFloat32AVX2Kernel(src uintptr, dst uintptr, n int)

func int16ToFloat32AVX2Kernel(src uintptr, dst uintptr, n int)

func uint16ToFloat32AVX2Kernel(src uintptr, dst uintptr, n int)

func int32ToFloat32AVX2Kernel(src uintptr, dst uintptr, n int)

func uint32ToFloat32AVX2Kernel(src uintptr, dst uintptr, n int)

func float16ToFloat32AVX2Kernel(src uintptr, dst uintptr, n int)

func int8ToFloat32AVX512Kernel(src uintptr, dst uintptr, n int)

func uint8ToFloat32AVX512Kernel(src uintptr, dst uintptr, n int)

func int16ToFloat32AVX512Kernel(src uintptr, dst uintptr, n int)

func uint16ToFloat32AVX512Kernel(src uintptr, dst uintptr, n int)

func int32ToFloat32AVX512Kernel(src uintptr, dst uintptr, n int)

func uint32ToFloat32AVX512Kernel(src uintptr, dst uintptr, n int)

func float16ToFloat32AVX512Kernel(src uintptr, dst uintptr, n int)

func softmaxAVX512Kernel(src uintptr, dst uintptr, n int)

func matchInt64AVX2Kernel(src uintptr, val int64, op int, dst uintptr, n int)

func matchInt32AVX2Kernel(src uintptr, val int64, op int, dst uintptr, n int)

func matchFloat32AVX2Kernel(src uintptr, val int64, op int, dst uintptr, n int)

func matchFloat64AVX2Kernel(src uintptr, val int64, op int, dst uintptr, n int)

func matchInt64AVX512Kernel(src uintptr, val int64, op int, dst uintptr, n int)

func matchInt32AVX512Kernel(src uintptr, val int64, op int, dst uintptr, n int)

func matchFloat32AVX512Kernel(src uintptr, val int64, op int, dst uintptr, n int)

func matchFloat64AVX512Kernel(src uintptr, val int64, op int, dst uintptr, n int)

func cosineDotAVX512(a uintptr, b uintptr, n int) (dot float32, normA float32, normB float32)

func euclideanVertical4AVX512(q uintptr, v0 uintptr, v1 uintptr, v2 uintptr, v3 uintptr, n int, res uintptr)

func cosineVertical4AVX512(q uintptr, v0 uintptr, v1 uintptr, v2 uintptr, v3 uintptr, n int, res uintptr)

func dotVertical4AVX512(q uintptr, v0 uintptr, v1 uintptr, v2 uintptr, v3 uintptr, n int, res uintptr)

func euclideanVertical4AVX2(q uintptr, v0 uintptr, v1 uintptr, v2 uintptr, v3 uintptr, n int, res uintptr)

func dotVertical4AVX2(q uintptr, v0 uintptr, v1 uintptr, v2 uintptr, v3 uintptr, n int, res uintptr)

func cosineVertical4AVX2(q uintptr, v0 uintptr, v1 uintptr, v2 uintptr, v3 uintptr, n int, res uintptr)

func euclideanSQ8AVX512Kernel(a uintptr, b uintptr, n int) int32

func adcBatchAVX512Kernel(table uintptr, codes uintptr, m int, results uintptr, n int)

func adcBatchVNNIKernel(table uintptr, codes uintptr, m int, results uintptr, n int)

func euclideanPQVNNIKernel(q uintptr, c uintptr, subDim int, k int, res uintptr)

func adcBatchAVX2Kernel(table uintptr, codes uintptr, m int, results uintptr, n int)

func euclideanSQ8AVX2Kernel(a uintptr, b uintptr, n int) int32

func cosine8AVX2(a uintptr, b uintptr) (dot float32, normA float32, normB float32)

func l2SquaredAVX2Kernel(a uintptr, b uintptr, n int, res uintptr)

func dotAVX2Kernel(a uintptr, b uintptr, n int, res uintptr)

func euclidean384AVX512Kernel(a uintptr, b uintptr) float32

func euclidean768AVX512Kernel(a uintptr, b uintptr) float32

func euclidean1536AVX512Kernel(a uintptr, b uintptr) float32

func dot384AVX512Kernel(a uintptr, b uintptr) float32

func dot768AVX512Kernel(a uintptr, b uintptr) float32

func dot1536AVX512Kernel(a uintptr, b uintptr) float32

func euclidean32FMA(a uintptr, b uintptr) float32

func dot32FMA(a uintptr, b uintptr) float32

func cosine32FMA(a uintptr, b uintptr) (dot float32, normA float32, normB float32)

func euclidean64FMA(a uintptr, b uintptr) float32

func dot64FMA(a uintptr, b uintptr) float32

func cosine64FMA(a uintptr, b uintptr) (dot float32, normA float32, normB float32)

func matMulAVX2(a uintptr, b uintptr, dst uintptr, m int, n int, k int)

func argMaxAVX2Kernel(src uintptr, n int) (val float32, idx int)

func argMinAVX2Kernel(src uintptr, n int) (val float32, idx int)

func argMaxAVX512Kernel(src uintptr, n int) (val float32, idx int)

func argMinAVX512Kernel(src uintptr, n int) (val float32, idx int)

func expAVX2Kernel(src uintptr, dst uintptr, n int)

func logAVX2Kernel(src uintptr, dst uintptr, n int)

func softmaxAVX2Kernel(src uintptr, dst uintptr, n int)

func sigmoidAVX2Kernel(src uintptr, dst uintptr, n int)
