// Code generated by command: go run all_kernels_gen.go -out all_kernels_avo_amd64.s -pkg simd. DO NOT EDIT.

#include "textflag.h"

// func euclidean8AVX2(a uintptr, b uintptr) float32
// Requires: AVX, SSE
TEXT ·euclidean8AVX2(SB), NOSPLIT, $0-20
	MOVQ         a+0(FP), AX
	MOVQ         b+8(FP), CX
	VMOVUPS      (AX), Y0
	VMOVUPS      (CX), Y1
	VSUBPS       Y1, Y0, Y0
	VMULPS       Y0, Y0, Y0
	VEXTRACTF128 $0x00, Y0, X1
	VEXTRACTF128 $0x01, Y0, X0
	VADDPS       X1, X0, X0
	VMOVHLPS     X0, X2, X2
	VADDPS       X2, X0, X0
	VMOVSHDUP    X0, X1
	VADDSS       X1, X0, X0
	MOVSS        X0, ret+16(FP)
	VZEROUPPER
	RET

// func dot8AVX2(a uintptr, b uintptr) float32
// Requires: AVX, SSE
TEXT ·dot8AVX2(SB), NOSPLIT, $0-20
	MOVQ         a+0(FP), AX
	MOVQ         b+8(FP), CX
	VMOVUPS      (AX), Y0
	VMOVUPS      (CX), Y1
	VMULPS       Y0, Y1, Y0
	VEXTRACTF128 $0x00, Y0, X1
	VEXTRACTF128 $0x01, Y0, X0
	VADDPS       X1, X0, X0
	VMOVHLPS     X0, X2, X2
	VADDPS       X2, X0, X0
	VMOVSHDUP    X0, X1
	VADDSS       X1, X0, X0
	MOVSS        X0, ret+16(FP)
	VZEROUPPER
	RET

// func euclidean16AVX512(a uintptr, b uintptr) float32
// Requires: AVX, AVX512F, SSE
TEXT ·euclidean16AVX512(SB), NOSPLIT, $0-20
	MOVQ          a+0(FP), AX
	MOVQ          b+8(FP), CX
	VMOVUPS       (AX), Z0
	VMOVUPS       (CX), Z1
	VSUBPS        Z1, Z0, Z0
	VMULPS        Z0, Z0, Z0
	VEXTRACTF64X4 $0x00, Z0, Y1
	VEXTRACTF64X4 $0x01, Z0, Y0
	VADDPS        Y1, Y0, Y0
	VEXTRACTF128  $0x00, Y0, X1
	VEXTRACTF128  $0x01, Y0, X0
	VADDPS        X1, X0, X0
	VMOVHLPS      X0, X2, X2
	VADDPS        X2, X0, X0
	VMOVSHDUP     X0, X1
	VADDSS        X1, X0, X0
	MOVSS         X0, ret+16(FP)
	VZEROUPPER
	RET

// func dot16AVX512(a uintptr, b uintptr) float32
// Requires: AVX, AVX512DQ, AVX512F, SSE
TEXT ·dot16AVX512(SB), NOSPLIT, $0-20
	MOVQ          a+0(FP), AX
	MOVQ          b+8(FP), CX
	VXORPS        Z0, Z0, Z0
	VMOVUPS       (AX), Z1
	VMOVUPS       (CX), Z2
	VFMADD231PS   Z1, Z2, Z0
	VEXTRACTF64X4 $0x00, Z0, Y1
	VEXTRACTF64X4 $0x01, Z0, Y0
	VADDPS        Y1, Y0, Y0
	VEXTRACTF128  $0x00, Y0, X1
	VEXTRACTF128  $0x01, Y0, X0
	VADDPS        X1, X0, X0
	VMOVHLPS      X0, X3, X3
	VADDPS        X3, X0, X0
	VMOVSHDUP     X0, X1
	VADDSS        X1, X0, X0
	MOVSS         X0, ret+16(FP)
	VZEROUPPER
	RET

// func prefetchNTA(p uintptr)
// Requires: MMX+
TEXT ·prefetchNTA(SB), NOSPLIT, $0-8
	MOVQ        p+0(FP), AX
	PREFETCHNTA (AX)
	RET

// func matchInt64AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·matchInt64AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func matchInt32AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·matchInt32AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func matchFloat32AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·matchFloat32AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func matchFloat64AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·matchFloat64AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanFloat64AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanFloat64AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanInt8AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanInt8AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanInt16AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanInt16AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanInt8Unrolled4xAVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanInt8Unrolled4xAVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanUint16AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanUint16AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func dotInt16AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotInt16AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func dotUint16AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotUint16AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func int8ToFloat32AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·int8ToFloat32AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func uint8ToFloat32AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·uint8ToFloat32AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func int16ToFloat32AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·int16ToFloat32AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func uint16ToFloat32AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·uint16ToFloat32AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func int32ToFloat32AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·int32ToFloat32AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func uint32ToFloat32AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·uint32ToFloat32AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func float16ToFloat32AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·float16ToFloat32AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func sigmoidAVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·sigmoidAVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func softmaxAVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·softmaxAVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func expAVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·expAVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func logAVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·logAVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func sigmoidAVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·sigmoidAVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func expAVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·expAVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func logAVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·logAVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func l2SquaredAVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·l2SquaredAVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func dotAVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotAVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func cosineDotAVX512(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·cosineDotAVX512(SB), NOSPLIT, $0-56
	RET

// func euclideanVertical4AVX512(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanVertical4AVX512(SB), NOSPLIT, $0-56
	RET

// func cosineVertical4AVX512(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·cosineVertical4AVX512(SB), NOSPLIT, $0-56
	RET

// func dotVertical4AVX512(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotVertical4AVX512(SB), NOSPLIT, $0-56
	RET

// func matchInt64AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·matchInt64AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func matchInt32AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·matchInt32AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func matchFloat32AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·matchFloat32AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func matchFloat64AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·matchFloat64AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanFloat64AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanFloat64AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func dotFloat64AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotFloat64AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanSQ8AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanSQ8AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanF16AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanF16AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func dotF16AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotF16AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func adcBatchAVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·adcBatchAVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func adcBatchVNNIKernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·adcBatchVNNIKernel(SB), NOSPLIT, $0-56
	RET

// func euclideanPQVNNIKernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanPQVNNIKernel(SB), NOSPLIT, $0-56
	RET

// func l2SquaredAVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·l2SquaredAVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func dotAVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotAVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanF16AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanF16AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func dotF16AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotF16AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func adcBatchAVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·adcBatchAVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func dotInt4AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotInt4AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func dotInt4AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotInt4AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanVertical4AVX2(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanVertical4AVX2(SB), NOSPLIT, $0-56
	RET

// func euclideanSQ8AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanSQ8AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func euclidean32FMA(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclidean32FMA(SB), NOSPLIT, $0-56
	RET

// func dot32FMA(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dot32FMA(SB), NOSPLIT, $0-56
	RET

// func cosine32FMA(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·cosine32FMA(SB), NOSPLIT, $0-56
	RET

// func euclidean64FMA(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclidean64FMA(SB), NOSPLIT, $0-56
	RET

// func dot64FMA(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dot64FMA(SB), NOSPLIT, $0-56
	RET

// func cosine64FMA(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·cosine64FMA(SB), NOSPLIT, $0-56
	RET

// func int8ToFloat32AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·int8ToFloat32AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func uint8ToFloat32AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·uint8ToFloat32AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func int16ToFloat32AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·int16ToFloat32AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func uint16ToFloat32AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·uint16ToFloat32AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func int32ToFloat32AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·int32ToFloat32AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func uint32ToFloat32AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·uint32ToFloat32AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func float16ToFloat32AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·float16ToFloat32AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func dotFloat64AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotFloat64AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func cosine8AVX2(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·cosine8AVX2(SB), NOSPLIT, $0-56
	RET

// func dotVertical4AVX2(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotVertical4AVX2(SB), NOSPLIT, $0-56
	RET

// func cosineVertical4AVX2(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·cosineVertical4AVX2(SB), NOSPLIT, $0-56
	RET
