// Code generated by command: go run all_kernels_gen.go -out internal/simd/all_kernels_avo_amd64.s -pkg simd. DO NOT EDIT.

#include "textflag.h"

// func euclidean8AVX2(a uintptr, b uintptr) float32
// Requires: AVX, SSE
TEXT ·euclidean8AVX2(SB), NOSPLIT, $0-20
	MOVQ         a+0(FP), AX
	MOVQ         b+8(FP), CX
	VMOVUPS      (AX), Y0
	VMOVUPS      (CX), Y1
	VSUBPS       Y1, Y0, Y0
	VMULPS       Y0, Y0, Y0
	VEXTRACTF128 $0x00, Y0, X1
	VEXTRACTF128 $0x01, Y0, X0
	VADDPS       X1, X0, X0
	VMOVHLPS     X0, X2, X2
	VADDPS       X2, X0, X0
	VMOVSHDUP    X0, X1
	VADDSS       X1, X0, X0
	MOVSS        X0, ret+16(FP)
	VZEROUPPER
	RET

// func dot8AVX2(a uintptr, b uintptr) float32
// Requires: AVX, SSE
TEXT ·dot8AVX2(SB), NOSPLIT, $0-20
	MOVQ         a+0(FP), AX
	MOVQ         b+8(FP), CX
	VMOVUPS      (AX), Y0
	VMOVUPS      (CX), Y1
	VMULPS       Y0, Y1, Y0
	VEXTRACTF128 $0x00, Y0, X1
	VEXTRACTF128 $0x01, Y0, X0
	VADDPS       X1, X0, X0
	VMOVHLPS     X0, X2, X2
	VADDPS       X2, X0, X0
	VMOVSHDUP    X0, X1
	VADDSS       X1, X0, X0
	MOVSS        X0, ret+16(FP)
	VZEROUPPER
	RET

// func euclidean16AVX512(a uintptr, b uintptr) float32
// Requires: AVX, AVX512F, SSE
TEXT ·euclidean16AVX512(SB), NOSPLIT, $0-20
	MOVQ          a+0(FP), AX
	MOVQ          b+8(FP), CX
	VMOVUPS       (AX), Z0
	VMOVUPS       (CX), Z1
	VSUBPS        Z1, Z0, Z0
	VMULPS        Z0, Z0, Z0
	VEXTRACTF64X4 $0x00, Z0, Y1
	VEXTRACTF64X4 $0x01, Z0, Y0
	VADDPS        Y1, Y0, Y0
	VEXTRACTF128  $0x00, Y0, X1
	VEXTRACTF128  $0x01, Y0, X0
	VADDPS        X1, X0, X0
	VMOVHLPS      X0, X2, X2
	VADDPS        X2, X0, X0
	VMOVSHDUP     X0, X1
	VADDSS        X1, X0, X0
	MOVSS         X0, ret+16(FP)
	VZEROUPPER
	RET

// func dot16AVX512(a uintptr, b uintptr) float32
// Requires: AVX, AVX512DQ, AVX512F, SSE
TEXT ·dot16AVX512(SB), NOSPLIT, $0-20
	MOVQ          a+0(FP), AX
	MOVQ          b+8(FP), CX
	VXORPS        Z0, Z0, Z0
	VMOVUPS       (AX), Z1
	VMOVUPS       (CX), Z2
	VFMADD231PS   Z1, Z2, Z0
	VEXTRACTF64X4 $0x00, Z0, Y1
	VEXTRACTF64X4 $0x01, Z0, Y0
	VADDPS        Y1, Y0, Y0
	VEXTRACTF128  $0x00, Y0, X1
	VEXTRACTF128  $0x01, Y0, X0
	VADDPS        X1, X0, X0
	VMOVHLPS      X0, X3, X3
	VADDPS        X3, X0, X0
	VMOVSHDUP     X0, X1
	VADDSS        X1, X0, X0
	MOVSS         X0, ret+16(FP)
	VZEROUPPER
	RET

// func prefetchNTA(p uintptr)
// Requires: MMX+
TEXT ·prefetchNTA(SB), NOSPLIT, $0-8
	MOVQ        p+0(FP), AX
	PREFETCHNTA (AX)
	RET

DATA neg_inf_const_red<>+0(SB)/4, $0xff800000
GLOBL neg_inf_const_red<>(SB), RODATA|NOPTR, $4

DATA pos_inf_const_red<>+0(SB)/4, $0x7f800000
GLOBL pos_inf_const_red<>(SB), RODATA|NOPTR, $4

// func sumAVX2Kernel(src uintptr, n int) float32
// Requires: AVX, SSE
TEXT ·sumAVX2Kernel(SB), NOSPLIT, $0-20
	MOVQ   src+0(FP), AX
	MOVQ   n+8(FP), CX
	VXORPS Y0, Y0, Y0

sum_loop:
	CMPQ    CX, $0x08
	JL      sum_tail
	VMOVUPS (AX), Y1
	VADDPS  Y1, Y0, Y0
	ADDQ    $0x20, AX
	SUBQ    $0x08, CX
	JMP     sum_loop

sum_tail:
	VEXTRACTF128 $0x00, Y0, X1
	VEXTRACTF128 $0x01, Y0, X0
	VADDPS       X1, X0, X0
	VMOVHLPS     X0, X2, X2
	VADDPS       X2, X0, X0
	VMOVSHDUP    X0, X1
	VADDSS       X1, X0, X0
	MOVSS        X0, ret+16(FP)
	VZEROUPPER
	RET

// func maxAVX2Kernel(src uintptr, n int) float32
// Requires: AVX, SSE
TEXT ·maxAVX2Kernel(SB), NOSPLIT, $0-20
	MOVQ         src+0(FP), AX
	MOVQ         n+8(FP), CX
	VBROADCASTSS neg_inf_const_red<>+0(SB), Y0

max_loop:
	CMPQ    CX, $0x08
	JL      max_tail
	VMOVUPS (AX), Y1
	VMAXPS  Y1, Y0, Y0
	ADDQ    $0x20, AX
	SUBQ    $0x08, CX
	JMP     max_loop

max_tail:
	VEXTRACTF128 $0x00, Y0, X1
	VEXTRACTF128 $0x01, Y0, X0
	VMAXPS       X1, X0, X0
	VMOVSHDUP    X0, X1
	VMAXSS       X1, X0, X0
	VPERMILPS    $0x4e, X0, X1
	VMAXSS       X1, X0, X0
	MOVSS        X0, ret+16(FP)
	VZEROUPPER
	RET

// func minAVX2Kernel(src uintptr, n int) float32
// Requires: AVX, SSE
TEXT ·minAVX2Kernel(SB), NOSPLIT, $0-20
	MOVQ         src+0(FP), AX
	MOVQ         n+8(FP), CX
	VBROADCASTSS pos_inf_const_red<>+0(SB), Y0

min_loop:
	CMPQ    CX, $0x08
	JL      min_tail
	VMOVUPS (AX), Y1
	VMINPS  Y1, Y0, Y0
	ADDQ    $0x20, AX
	SUBQ    $0x08, CX
	JMP     min_loop

min_tail:
	VEXTRACTF128 $0x00, Y0, X1
	VEXTRACTF128 $0x01, Y0, X0
	VMINPS       X1, X0, X0
	VMOVSHDUP    X0, X1
	VMINSS       X1, X0, X0
	VPERMILPS    $0x4e, X0, X1
	VMINSS       X1, X0, X0
	MOVSS        X0, ret+16(FP)
	VZEROUPPER
	RET

// func matchInt64AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·matchInt64AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func matchInt32AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·matchInt32AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func matchFloat32AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·matchFloat32AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func matchFloat64AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·matchFloat64AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanFloat64AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanFloat64AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanInt8AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanInt8AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanInt16AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanInt16AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanInt8Unrolled4xAVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanInt8Unrolled4xAVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanUint16AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanUint16AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func dotInt16AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotInt16AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func dotUint16AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotUint16AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func int8ToFloat32AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·int8ToFloat32AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func uint8ToFloat32AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·uint8ToFloat32AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func int16ToFloat32AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·int16ToFloat32AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func uint16ToFloat32AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·uint16ToFloat32AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func int32ToFloat32AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·int32ToFloat32AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func uint32ToFloat32AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·uint32ToFloat32AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func float16ToFloat32AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·float16ToFloat32AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func sigmoidAVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·sigmoidAVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func expAVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·expAVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func logAVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·logAVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func l2SquaredAVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·l2SquaredAVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func dotAVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotAVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func cosineDotAVX512(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·cosineDotAVX512(SB), NOSPLIT, $0-56
	RET

// func euclideanVertical4AVX512(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanVertical4AVX512(SB), NOSPLIT, $0-56
	RET

// func cosineVertical4AVX512(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·cosineVertical4AVX512(SB), NOSPLIT, $0-56
	RET

// func dotVertical4AVX512(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotVertical4AVX512(SB), NOSPLIT, $0-56
	RET

// func matchInt64AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·matchInt64AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func matchInt32AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·matchInt32AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func matchFloat32AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·matchFloat32AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func matchFloat64AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·matchFloat64AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanFloat64AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanFloat64AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func dotFloat64AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotFloat64AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanSQ8AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanSQ8AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanF16AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanF16AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func dotF16AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotF16AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func adcBatchAVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·adcBatchAVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func adcBatchVNNIKernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·adcBatchVNNIKernel(SB), NOSPLIT, $0-56
	RET

// func euclideanPQVNNIKernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanPQVNNIKernel(SB), NOSPLIT, $0-56
	RET

// func l2SquaredAVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·l2SquaredAVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func dotAVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotAVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanF16AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanF16AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func dotF16AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotF16AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func adcBatchAVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·adcBatchAVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func dotInt4AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotInt4AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func dotInt4AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotInt4AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func euclideanVertical4AVX2(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanVertical4AVX2(SB), NOSPLIT, $0-56
	RET

// func euclideanSQ8AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclideanSQ8AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func euclidean32FMA(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclidean32FMA(SB), NOSPLIT, $0-56
	RET

// func dot32FMA(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dot32FMA(SB), NOSPLIT, $0-56
	RET

// func cosine32FMA(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·cosine32FMA(SB), NOSPLIT, $0-56
	RET

// func euclidean64FMA(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·euclidean64FMA(SB), NOSPLIT, $0-56
	RET

// func dot64FMA(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dot64FMA(SB), NOSPLIT, $0-56
	RET

// func cosine64FMA(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·cosine64FMA(SB), NOSPLIT, $0-56
	RET

// func int8ToFloat32AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·int8ToFloat32AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func uint8ToFloat32AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·uint8ToFloat32AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func int16ToFloat32AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·int16ToFloat32AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func uint16ToFloat32AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·uint16ToFloat32AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func int32ToFloat32AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·int32ToFloat32AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func uint32ToFloat32AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·uint32ToFloat32AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func float16ToFloat32AVX512Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·float16ToFloat32AVX512Kernel(SB), NOSPLIT, $0-56
	RET

// func dotFloat64AVX2Kernel(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotFloat64AVX2Kernel(SB), NOSPLIT, $0-56
	RET

// func cosine8AVX2(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·cosine8AVX2(SB), NOSPLIT, $0-56
	RET

// func dotVertical4AVX2(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·dotVertical4AVX2(SB), NOSPLIT, $0-56
	RET

// func cosineVertical4AVX2(a uintptr, b uintptr, c uintptr, d uintptr, e uintptr, f uintptr, g uintptr)
TEXT ·cosineVertical4AVX2(SB), NOSPLIT, $0-56
	RET

// func matMulAVX2(a uintptr, b uintptr, dst uintptr, m int, n int, k int)
// Requires: AVX, FMA3
TEXT ·matMulAVX2(SB), NOSPLIT, $0-48
	MOVQ a+0(FP), AX
	MOVQ b+8(FP), CX
	MOVQ dst+16(FP), DX
	MOVQ m+24(FP), BX
	MOVQ n+32(FP), SI
	MOVQ k+40(FP), DI
	XORQ R8, R8

mat_row_loop:
	CMPQ R8, BX
	JGE  mat_done
	XORQ R9, R9

mat_col_loop:
	CMPQ   R9, SI
	JGE    mat_next_row
	VXORPS X0, X0, X0
	XORQ   R10, R10

mat_sum_loop:
	CMPQ        R10, DI
	JGE         mat_store_result
	MOVQ        R8, R11
	IMULQ       DI, R11
	ADDQ        R10, R11
	SHLQ        $0x02, R11
	MOVQ        R10, R12
	IMULQ       SI, R12
	ADDQ        R9, R12
	SHLQ        $0x02, R12
	VMOVSS      (AX)(R11*1), X1
	VMOVSS      (CX)(R12*1), X2
	VFMADD231SS X1, X2, X0
	ADDQ        $0x01, R10
	JMP         mat_sum_loop

mat_store_result:
	MOVQ   R8, R10
	IMULQ  SI, R10
	ADDQ   R9, R10
	SHLQ   $0x02, R10
	VMOVSS X0, (DX)(R10*1)
	ADDQ   $0x01, R9
	JMP    mat_col_loop

mat_next_row:
	ADDQ $0x01, R8
	JMP  mat_row_loop

mat_done:
	RET

// func expAVX2Kernel(src uintptr, dst uintptr, n int)
// Requires: AVX, FMA3, SSE
TEXT ·expAVX2Kernel(SB), NOSPLIT, $0-24
	MOVQ src+0(FP), AX
	MOVQ dst+8(FP), CX
	MOVQ n+16(FP), DX

exp_loop:
	CMPQ         DX, $0x08
	JL           exp_tail
	VMOVUPS      (AX), Y0
	VBROADCASTSS exp_p5<>+0(SB), Y1
	VBROADCASTSS exp_p4<>+0(SB), Y2
	VFMADD213PS  Y2, Y0, Y1
	VBROADCASTSS exp_p3<>+0(SB), Y2
	VFMADD213PS  Y2, Y0, Y1
	VBROADCASTSS exp_p2<>+0(SB), Y2
	VFMADD213PS  Y2, Y0, Y1
	VBROADCASTSS exp_p1<>+0(SB), Y2
	VFMADD213PS  Y2, Y0, Y1
	VBROADCASTSS exp_p0<>+0(SB), Y2
	VFMADD213PS  Y2, Y0, Y1
	VMOVUPS      Y1, (CX)
	ADDQ         $0x20, AX
	ADDQ         $0x20, CX
	SUBQ         $0x08, DX
	JMP          exp_loop

exp_tail:
	CMPQ   DX, $0x00
	JE     exp_done
	VMOVSS (AX), X0
	VXORPS X1, X1, X1
	MOVSS  exp_p1<>+0(SB), X1
	VADDSS X1, X0, X0
	VMOVSS X0, (CX)
	ADDQ   $0x04, AX
	ADDQ   $0x04, CX
	DECQ   DX
	JMP    exp_tail

exp_done:
	RET

DATA exp_p0<>+0(SB)/4, $(1.0)
GLOBL exp_p0<>(SB), RODATA|NOPTR, $4

DATA exp_p1<>+0(SB)/4, $(1.0)
GLOBL exp_p1<>(SB), RODATA|NOPTR, $4

DATA exp_p2<>+0(SB)/4, $(0.5)
GLOBL exp_p2<>(SB), RODATA|NOPTR, $4

DATA exp_p3<>+0(SB)/4, $(0.16666667)
GLOBL exp_p3<>(SB), RODATA|NOPTR, $4

DATA exp_p4<>+0(SB)/4, $(0.041666664)
GLOBL exp_p4<>(SB), RODATA|NOPTR, $4

DATA exp_p5<>+0(SB)/4, $(0.008333333)
GLOBL exp_p5<>(SB), RODATA|NOPTR, $4

// func logAVX2Kernel(src uintptr, dst uintptr, n int)
// Requires: AVX, FMA3, SSE
TEXT ·logAVX2Kernel(SB), NOSPLIT, $0-24
	MOVQ src+0(FP), AX
	MOVQ dst+8(FP), CX
	MOVQ n+16(FP), DX

log_loop:
	CMPQ         DX, $0x08
	JL           log_tail
	VMOVUPS      (AX), Y0
	VBROADCASTSS log_one<>+0(SB), Y1
	VSUBPS       Y1, Y0, Y0
	VBROADCASTSS log_c2<>+0(SB), Y2
	VBROADCASTSS log_c1<>+0(SB), Y3
	VFMADD213PS  Y3, Y0, Y2
	VFMADD213PS  Y1, Y0, Y2
	VMULPS       Y0, Y2, Y2
	VMOVUPS      Y2, (CX)
	ADDQ         $0x20, AX
	ADDQ         $0x20, CX
	SUBQ         $0x08, DX
	JMP          log_loop

log_tail:
	CMPQ   DX, $0x00
	JE     log_done
	VMOVSS (AX), X0
	VXORPS X1, X1, X1
	MOVSS  log_one<>+0(SB), X1
	VSUBSS X1, X0, X0
	VMOVSS X0, (CX)
	ADDQ   $0x04, AX
	ADDQ   $0x04, CX
	DECQ   DX
	JMP    log_tail

log_done:
	RET

DATA log_one<>+0(SB)/4, $(1.0)
GLOBL log_one<>(SB), RODATA|NOPTR, $4

DATA log_c1<>+0(SB)/4, $(-0.5)
GLOBL log_c1<>(SB), RODATA|NOPTR, $4

DATA log_c2<>+0(SB)/4, $(0.33333334)
GLOBL log_c2<>(SB), RODATA|NOPTR, $4

// func softmaxAVX2Kernel(src uintptr, dst uintptr, n int)
TEXT ·softmaxAVX2Kernel(SB), NOSPLIT, $0-24
	RET

// func sigmoidAVX2Kernel(src uintptr, dst uintptr, n int)
// Requires: AVX, SSE
TEXT ·sigmoidAVX2Kernel(SB), NOSPLIT, $0-24
	MOVQ src+0(FP), AX
	MOVQ dst+8(FP), CX
	MOVQ n+16(FP), DX

sig_loop:
	CMPQ         DX, $0x08
	JL           sig_tail
	VMOVUPS      (AX), Y0
	VXORPS       Y1, Y1, Y1
	VSUBPS       Y0, Y1, Y1
	VBROADCASTSS sig_p1<>+0(SB), Y0
	VADDPS       Y1, Y0, Y0
	VBROADCASTSS sig_p1<>+0(SB), Y1
	VADDPS       Y1, Y0, Y0
	VDIVPS       Y0, Y1, Y0
	VMOVUPS      Y0, (CX)
	ADDQ         $0x20, AX
	ADDQ         $0x20, CX
	SUBQ         $0x08, DX
	JMP          sig_loop

sig_tail:
	CMPQ   DX, $0x00
	JE     sig_done
	VMOVSS (AX), X0
	MOVSS  sig_p1<>+0(SB), X1
	MOVSS  sig_p1<>+0(SB), X2
	ADDSS  X2, X2
	SUBSS  X0, X2
	DIVSS  X2, X1
	VMOVSS X1, (CX)
	ADDQ   $0x04, AX
	ADDQ   $0x04, CX
	DECQ   DX
	JMP    sig_tail

sig_done:
	RET

DATA sig_p1<>+0(SB)/4, $(1.0)
GLOBL sig_p1<>(SB), RODATA|NOPTR, $4
