// Code generated by command: go run kernels_gen.go -out kernels_avo_amd64.s -pkg simd. DO NOT EDIT.

#include "textflag.h"

// func euclidean8AVX2_New(a uintptr, b uintptr) float32
// Requires: AVX, SSE
TEXT ·euclidean8AVX2_New(SB), NOSPLIT, $0-20
	MOVQ         a+0(FP), AX
	MOVQ         b+8(FP), CX
	VMOVUPS      (AX), Y0
	VMOVUPS      (CX), Y1
	VSUBPS       Y1, Y0, Y0
	VMULPS       Y0, Y0, Y0
	VEXTRACTF128 $0x00, Y0, X1
	VEXTRACTF128 $0x01, Y0, X0
	VADDPS       X1, X0, X0
	VMOVHLPS     X0, X2, X2
	VADDPS       X2, X0, X0
	VMOVSHDUP    X0, X1
	VADDSS       X1, X0, X0
	MOVSS        X0, ret+16(FP)
	VZEROUPPER
	RET

// func dot8AVX2_New(a uintptr, b uintptr) float32
// Requires: AVX, SSE
TEXT ·dot8AVX2_New(SB), NOSPLIT, $0-20
	MOVQ         a+0(FP), AX
	MOVQ         b+8(FP), CX
	VMOVUPS      (AX), Y0
	VMOVUPS      (CX), Y1
	VMULPS       Y0, Y1, Y0
	VEXTRACTF128 $0x00, Y0, X1
	VEXTRACTF128 $0x01, Y0, X0
	VADDPS       X1, X0, X0
	VMOVHLPS     X0, X2, X2
	VADDPS       X2, X0, X0
	VMOVSHDUP    X0, X1
	VADDSS       X1, X0, X0
	MOVSS        X0, ret+16(FP)
	VZEROUPPER
	RET
