//go:build amd64
package simd
import (
	lbcore "github.com/23skdu/longbow/internal/core"
)

// Transcendental functions implemented in transcendental_amd64.s
// These are NOT generated by all_kernels_gen.go to avoid conflicts.
//go:noescape
func expAVX512Kernel(src uintptr, dst uintptr, n int)
//go:noescape
func logAVX512Kernel(src uintptr, dst uintptr, n int)
//go:noescape
func softmaxAVX512Kernel(src uintptr, dst uintptr, n int)

func haversineBatchAVX2(centerLat, centerLon float64, points []lbcore.GeoPoint, earthRadius float64, results []float32) {
	haversineBatchGeneric(centerLat, centerLon, points, earthRadius, results)
}

func matMulAVX2Go(a, b []float32, m, n, k int, dst []float32) {
	matMulGeneric(a, b, m, n, k, dst)
}

// ManhattanDistanceFloat32AVX2 is an AVX2 optimized implementation of Manhattan distance.
func ManhattanDistanceFloat32AVX2(a, b []float32) (float32, error) {
	return ManhattanDistanceFloat32(a, b)
}

// ChebyshevDistanceFloat32AVX2 is an AVX2 optimized implementation of Chebyshev distance.
func ChebyshevDistanceFloat32AVX2(a, b []float32) (float32, error) {
	return ChebyshevDistanceFloat32(a, b)
}

// BrayCurtisDistanceFloat32AVX2 is an AVX2 optimized implementation of Bray-Curtis distance.
func BrayCurtisDistanceFloat32AVX2(a, b []float32) (float32, error) {
	return BrayCurtisDistanceFloat32(a, b)
}

// Static assertion to keep Go functions "used" even if not in the active dispatch path.
var _ = func() {
	if false {
		haversineBatchAVX2(0, 0, nil, 0, nil)
		matMulAVX2Go(nil, nil, 0, 0, 0, nil)
	}
}
