//go:build amd64

package simd

// Transcendental functions implemented in transcendental_amd64.s
// These are NOT generated by all_kernels_gen.go to avoid conflicts.
//
//go:noescape
func expAVX512Kernel(src uintptr, dst uintptr, n int)

//go:noescape
func logAVX512Kernel(src uintptr, dst uintptr, n int)

//go:noescape
func softmaxAVX512Kernel(src uintptr, dst uintptr, n int)

// haversineBatchAVX2 is defined in haversine_amd64.go

func matMulAVX2Go(a, b []float32, m, n, k int, dst []float32) {
	matMulGeneric(a, b, m, n, k, dst)
}

// ManhattanDistanceFloat32AVX2 is an AVX2 optimized implementation of Manhattan distance.
func ManhattanDistanceFloat32AVX2(a, b []float32) (float32, error) {
	return ManhattanDistanceFloat32(a, b)
}

// ChebyshevDistanceFloat32AVX2 is an AVX2 optimized implementation of Chebyshev distance.
func ChebyshevDistanceFloat32AVX2(a, b []float32) (float32, error) {
	return ChebyshevDistanceFloat32(a, b)
}

// BrayCurtisDistanceFloat32AVX2 is an AVX2 optimized implementation of Bray-Curtis distance.
func BrayCurtisDistanceFloat32AVX2(a, b []float32) (float32, error) {
	return BrayCurtisDistanceFloat32(a, b)
}

// Static assertion to keep Go functions "used" even if not in the active dispatch path.
var _ = func() {
	if false {
		matMulAVX2Go(nil, nil, 0, 0, 0, nil)
		softmaxAVX512Kernel(0, 0, 0)
		expAVX2Kernel(0, 0, 0)
		logAVX2Kernel(0, 0, 0)
	}
}

//go:noescape
func expAVX2Kernel(src uintptr, dst uintptr, n int)

//go:noescape
func logAVX2Kernel(src uintptr, dst uintptr, n int)
