//go:build amd64
package simd

// Transcendental functions implemented in transcendental_amd64.s
// These are NOT generated by all_kernels_gen.go to avoid conflicts.
//go:noescape
func expAVX512Kernel(src uintptr, dst uintptr, n int)
//go:noescape
func logAVX512Kernel(src uintptr, dst uintptr, n int)
//go:noescape
func softmaxAVX512Kernel(src uintptr, dst uintptr, n int)
