// Code generated by command: go run transcendentals_gen.go -out ../transcendental_avx2_amd64.s -pkg simd. DO NOT EDIT.

#include "textflag.h"

// func SinFloat32AVX2Kernel(src uintptr, dst uintptr, n int)
// Requires: AVX, FMA3
TEXT ·SinFloat32AVX2Kernel(SB), NOSPLIT, $0-24
	MOVQ    src+0(FP), AX
	MOVQ    dst+8(FP), CX
	MOVQ    n+16(FP), DX
	VMOVUPS sin_c1<>+0(SB), Y0
	VMOVUPS sin_c2<>+0(SB), Y1
	VMOVUPS sin_c3<>+0(SB), Y2

loop:
	CMPQ        DX, $0x08
	JL          tail
	VMOVUPS     (AX), Y3
	VMULPS      Y3, Y3, Y4
	VMOVUPS     Y2, Y5
	VFMADD213PS Y1, Y4, Y5
	VFMADD213PS Y0, Y4, Y5
	VMULPS      Y3, Y4, Y4
	VFMADD213PS Y3, Y4, Y5
	VMOVUPS     Y5, (CX)
	ADDQ        $0x20, AX
	ADDQ        $0x20, CX
	SUBQ        $0x08, DX
	JMP         loop

tail:
	CMPQ        DX, $0x00
	JE          done
	VMOVSS      (AX), X0
	VMULSS      X0, X0, X1
	VMOVSS      sin_c3<>+0(SB), X2
	VMOVSS      sin_c2<>+0(SB), X3
	VFMADD213SS X3, X1, X2
	VMOVSS      sin_c1<>+0(SB), X3
	VFMADD213SS X3, X1, X2
	VMULSS      X0, X1, X1
	VFMADD213SS X0, X1, X2
	VMOVSS      X2, (CX)
	ADDQ        $0x04, AX
	ADDQ        $0x04, CX
	DECQ        DX
	JMP         tail

done:
	VZEROUPPER
	RET

DATA sin_c1<>+0(SB)/4, $(-0.16666667)
DATA sin_c1<>+4(SB)/4, $(-0.16666667)
DATA sin_c1<>+8(SB)/4, $(-0.16666667)
DATA sin_c1<>+12(SB)/4, $(-0.16666667)
DATA sin_c1<>+16(SB)/4, $(-0.16666667)
DATA sin_c1<>+20(SB)/4, $(-0.16666667)
DATA sin_c1<>+24(SB)/4, $(-0.16666667)
DATA sin_c1<>+28(SB)/4, $(-0.16666667)
GLOBL sin_c1<>(SB), RODATA|NOPTR, $32

DATA sin_c2<>+0(SB)/4, $(0.008333334)
DATA sin_c2<>+4(SB)/4, $(0.008333334)
DATA sin_c2<>+8(SB)/4, $(0.008333334)
DATA sin_c2<>+12(SB)/4, $(0.008333334)
DATA sin_c2<>+16(SB)/4, $(0.008333334)
DATA sin_c2<>+20(SB)/4, $(0.008333334)
DATA sin_c2<>+24(SB)/4, $(0.008333334)
DATA sin_c2<>+28(SB)/4, $(0.008333334)
GLOBL sin_c2<>(SB), RODATA|NOPTR, $32

DATA sin_c3<>+0(SB)/4, $(-0.0001984127)
DATA sin_c3<>+4(SB)/4, $(-0.0001984127)
DATA sin_c3<>+8(SB)/4, $(-0.0001984127)
DATA sin_c3<>+12(SB)/4, $(-0.0001984127)
DATA sin_c3<>+16(SB)/4, $(-0.0001984127)
DATA sin_c3<>+20(SB)/4, $(-0.0001984127)
DATA sin_c3<>+24(SB)/4, $(-0.0001984127)
DATA sin_c3<>+28(SB)/4, $(-0.0001984127)
GLOBL sin_c3<>(SB), RODATA|NOPTR, $32

// func CosFloat32AVX2Kernel(src uintptr, dst uintptr, n int)
// Requires: AVX, FMA3
TEXT ·CosFloat32AVX2Kernel(SB), NOSPLIT, $0-24
	MOVQ    src+0(FP), AX
	MOVQ    dst+8(FP), CX
	MOVQ    n+16(FP), DX
	VMOVUPS cos_c0<>+0(SB), Y0
	VMOVUPS cos_c1<>+0(SB), Y1
	VMOVUPS cos_c2<>+0(SB), Y2
	VMOVUPS cos_c3<>+0(SB), Y3

loop:
	CMPQ        DX, $0x08
	JL          tail
	VMOVUPS     (AX), Y4
	VMULPS      Y4, Y4, Y4
	VMOVUPS     Y3, Y5
	VFMADD213PS Y2, Y4, Y5
	VFMADD213PS Y1, Y4, Y5
	VFMADD213PS Y0, Y4, Y5
	VMOVUPS     Y5, (CX)
	ADDQ        $0x20, AX
	ADDQ        $0x20, CX
	SUBQ        $0x08, DX
	JMP         loop

tail:
	CMPQ        DX, $0x00
	JE          done
	VMOVSS      (AX), X0
	VMULSS      X0, X0, X0
	VMOVSS      cos_c3<>+0(SB), X1
	VMOVSS      cos_c2<>+0(SB), X2
	VFMADD213SS X2, X0, X1
	VMOVSS      cos_c1<>+0(SB), X2
	VFMADD213SS X2, X0, X1
	VMOVSS      cos_c0<>+0(SB), X2
	VFMADD213SS X2, X0, X1
	VMOVSS      X1, (CX)
	ADDQ        $0x04, AX
	ADDQ        $0x04, CX
	DECQ        DX
	JMP         tail

done:
	VZEROUPPER
	RET

DATA cos_c0<>+0(SB)/4, $(1.0)
DATA cos_c0<>+4(SB)/4, $(1.0)
DATA cos_c0<>+8(SB)/4, $(1.0)
DATA cos_c0<>+12(SB)/4, $(1.0)
DATA cos_c0<>+16(SB)/4, $(1.0)
DATA cos_c0<>+20(SB)/4, $(1.0)
DATA cos_c0<>+24(SB)/4, $(1.0)
DATA cos_c0<>+28(SB)/4, $(1.0)
GLOBL cos_c0<>(SB), RODATA|NOPTR, $32

DATA cos_c1<>+0(SB)/4, $(-0.5)
DATA cos_c1<>+4(SB)/4, $(-0.5)
DATA cos_c1<>+8(SB)/4, $(-0.5)
DATA cos_c1<>+12(SB)/4, $(-0.5)
DATA cos_c1<>+16(SB)/4, $(-0.5)
DATA cos_c1<>+20(SB)/4, $(-0.5)
DATA cos_c1<>+24(SB)/4, $(-0.5)
DATA cos_c1<>+28(SB)/4, $(-0.5)
GLOBL cos_c1<>(SB), RODATA|NOPTR, $32

DATA cos_c2<>+0(SB)/4, $(0.041666668)
DATA cos_c2<>+4(SB)/4, $(0.041666668)
DATA cos_c2<>+8(SB)/4, $(0.041666668)
DATA cos_c2<>+12(SB)/4, $(0.041666668)
DATA cos_c2<>+16(SB)/4, $(0.041666668)
DATA cos_c2<>+20(SB)/4, $(0.041666668)
DATA cos_c2<>+24(SB)/4, $(0.041666668)
DATA cos_c2<>+28(SB)/4, $(0.041666668)
GLOBL cos_c2<>(SB), RODATA|NOPTR, $32

DATA cos_c3<>+0(SB)/4, $(-0.0013888889)
DATA cos_c3<>+4(SB)/4, $(-0.0013888889)
DATA cos_c3<>+8(SB)/4, $(-0.0013888889)
DATA cos_c3<>+12(SB)/4, $(-0.0013888889)
DATA cos_c3<>+16(SB)/4, $(-0.0013888889)
DATA cos_c3<>+20(SB)/4, $(-0.0013888889)
DATA cos_c3<>+24(SB)/4, $(-0.0013888889)
DATA cos_c3<>+28(SB)/4, $(-0.0013888889)
GLOBL cos_c3<>(SB), RODATA|NOPTR, $32

// func SincosFloat32AVX2Kernel(src uintptr, sinDst uintptr, cosDst uintptr, n int)
// Requires: AVX, FMA3
TEXT ·SincosFloat32AVX2Kernel(SB), NOSPLIT, $0-32
	MOVQ    src+0(FP), AX
	MOVQ    sinDst+8(FP), CX
	MOVQ    cosDst+16(FP), DX
	MOVQ    n+24(FP), BX
	VMOVUPS sincos_sin_c1<>+0(SB), Y0
	VMOVUPS sincos_sin_c2<>+0(SB), Y1
	VMOVUPS sincos_sin_c3<>+0(SB), Y2
	VMOVUPS sincos_cos_c0<>+0(SB), Y3
	VMOVUPS sincos_cos_c1<>+0(SB), Y4
	VMOVUPS sincos_cos_c2<>+0(SB), Y5
	VMOVUPS sincos_cos_c3<>+0(SB), Y6

loop:
	CMPQ        BX, $0x08
	JL          tail
	VMOVUPS     (AX), Y7
	VMULPS      Y7, Y7, Y8
	VMOVUPS     Y2, Y9
	VFMADD213PS Y1, Y8, Y9
	VFMADD213PS Y0, Y8, Y9
	VMULPS      Y7, Y8, Y10
	VFMADD213PS Y7, Y10, Y9
	VMOVUPS     Y9, (CX)
	VMOVUPS     Y6, Y7
	VFMADD213PS Y5, Y8, Y7
	VFMADD213PS Y4, Y8, Y7
	VFMADD213PS Y3, Y8, Y7
	VMOVUPS     Y7, (DX)
	ADDQ        $0x20, AX
	ADDQ        $0x20, CX
	ADDQ        $0x20, DX
	SUBQ        $0x08, BX
	JMP         loop

tail:
	CMPQ        BX, $0x00
	JE          done
	VMOVSS      (AX), X0
	VMULSS      X0, X0, X1
	VMOVSS      sincos_sin_c3<>+0(SB), X2
	VMOVSS      sincos_sin_c2<>+0(SB), X3
	VFMADD213SS X3, X1, X2
	VMOVSS      sincos_sin_c1<>+0(SB), X3
	VFMADD213SS X3, X1, X2
	VMULSS      X0, X1, X3
	VFMADD213SS X0, X3, X2
	VMOVSS      X2, (CX)
	VMOVSS      sincos_cos_c3<>+0(SB), X0
	VMOVSS      sincos_cos_c2<>+0(SB), X2
	VFMADD213SS X2, X1, X0
	VMOVSS      sincos_cos_c1<>+0(SB), X2
	VFMADD213SS X2, X1, X0
	VMOVSS      sincos_cos_c0<>+0(SB), X2
	VFMADD213SS X2, X1, X0
	VMOVSS      X0, (DX)
	ADDQ        $0x04, AX
	ADDQ        $0x04, CX
	ADDQ        $0x04, DX
	DECQ        BX
	JMP         tail

done:
	VZEROUPPER
	RET

DATA sincos_sin_c1<>+0(SB)/4, $(-0.16666667)
DATA sincos_sin_c1<>+4(SB)/4, $(-0.16666667)
DATA sincos_sin_c1<>+8(SB)/4, $(-0.16666667)
DATA sincos_sin_c1<>+12(SB)/4, $(-0.16666667)
DATA sincos_sin_c1<>+16(SB)/4, $(-0.16666667)
DATA sincos_sin_c1<>+20(SB)/4, $(-0.16666667)
DATA sincos_sin_c1<>+24(SB)/4, $(-0.16666667)
DATA sincos_sin_c1<>+28(SB)/4, $(-0.16666667)
GLOBL sincos_sin_c1<>(SB), RODATA|NOPTR, $32

DATA sincos_sin_c2<>+0(SB)/4, $(0.008333334)
DATA sincos_sin_c2<>+4(SB)/4, $(0.008333334)
DATA sincos_sin_c2<>+8(SB)/4, $(0.008333334)
DATA sincos_sin_c2<>+12(SB)/4, $(0.008333334)
DATA sincos_sin_c2<>+16(SB)/4, $(0.008333334)
DATA sincos_sin_c2<>+20(SB)/4, $(0.008333334)
DATA sincos_sin_c2<>+24(SB)/4, $(0.008333334)
DATA sincos_sin_c2<>+28(SB)/4, $(0.008333334)
GLOBL sincos_sin_c2<>(SB), RODATA|NOPTR, $32

DATA sincos_sin_c3<>+0(SB)/4, $(-0.0001984127)
DATA sincos_sin_c3<>+4(SB)/4, $(-0.0001984127)
DATA sincos_sin_c3<>+8(SB)/4, $(-0.0001984127)
DATA sincos_sin_c3<>+12(SB)/4, $(-0.0001984127)
DATA sincos_sin_c3<>+16(SB)/4, $(-0.0001984127)
DATA sincos_sin_c3<>+20(SB)/4, $(-0.0001984127)
DATA sincos_sin_c3<>+24(SB)/4, $(-0.0001984127)
DATA sincos_sin_c3<>+28(SB)/4, $(-0.0001984127)
GLOBL sincos_sin_c3<>(SB), RODATA|NOPTR, $32

DATA sincos_cos_c0<>+0(SB)/4, $(1.0)
DATA sincos_cos_c0<>+4(SB)/4, $(1.0)
DATA sincos_cos_c0<>+8(SB)/4, $(1.0)
DATA sincos_cos_c0<>+12(SB)/4, $(1.0)
DATA sincos_cos_c0<>+16(SB)/4, $(1.0)
DATA sincos_cos_c0<>+20(SB)/4, $(1.0)
DATA sincos_cos_c0<>+24(SB)/4, $(1.0)
DATA sincos_cos_c0<>+28(SB)/4, $(1.0)
GLOBL sincos_cos_c0<>(SB), RODATA|NOPTR, $32

DATA sincos_cos_c1<>+0(SB)/4, $(-0.5)
DATA sincos_cos_c1<>+4(SB)/4, $(-0.5)
DATA sincos_cos_c1<>+8(SB)/4, $(-0.5)
DATA sincos_cos_c1<>+12(SB)/4, $(-0.5)
DATA sincos_cos_c1<>+16(SB)/4, $(-0.5)
DATA sincos_cos_c1<>+20(SB)/4, $(-0.5)
DATA sincos_cos_c1<>+24(SB)/4, $(-0.5)
DATA sincos_cos_c1<>+28(SB)/4, $(-0.5)
GLOBL sincos_cos_c1<>(SB), RODATA|NOPTR, $32

DATA sincos_cos_c2<>+0(SB)/4, $(0.041666668)
DATA sincos_cos_c2<>+4(SB)/4, $(0.041666668)
DATA sincos_cos_c2<>+8(SB)/4, $(0.041666668)
DATA sincos_cos_c2<>+12(SB)/4, $(0.041666668)
DATA sincos_cos_c2<>+16(SB)/4, $(0.041666668)
DATA sincos_cos_c2<>+20(SB)/4, $(0.041666668)
DATA sincos_cos_c2<>+24(SB)/4, $(0.041666668)
DATA sincos_cos_c2<>+28(SB)/4, $(0.041666668)
GLOBL sincos_cos_c2<>(SB), RODATA|NOPTR, $32

DATA sincos_cos_c3<>+0(SB)/4, $(-0.0013888889)
DATA sincos_cos_c3<>+4(SB)/4, $(-0.0013888889)
DATA sincos_cos_c3<>+8(SB)/4, $(-0.0013888889)
DATA sincos_cos_c3<>+12(SB)/4, $(-0.0013888889)
DATA sincos_cos_c3<>+16(SB)/4, $(-0.0013888889)
DATA sincos_cos_c3<>+20(SB)/4, $(-0.0013888889)
DATA sincos_cos_c3<>+24(SB)/4, $(-0.0013888889)
DATA sincos_cos_c3<>+28(SB)/4, $(-0.0013888889)
GLOBL sincos_cos_c3<>(SB), RODATA|NOPTR, $32

// func Atan2Float32AVX2Kernel(y uintptr, x uintptr, dst uintptr, n int)
// Requires: AVX, FMA3
TEXT ·Atan2Float32AVX2Kernel(SB), NOSPLIT, $0-32
	MOVQ    y+0(FP), AX
	MOVQ    x+8(FP), CX
	MOVQ    dst+16(FP), DX
	MOVQ    n+24(FP), BX
	VMOVUPS atan_c1<>+0(SB), Y0
	VMOVUPS atan_c2<>+0(SB), Y1
	VMOVUPS atan_c3<>+0(SB), Y2
	VMOVUPS atan_c4<>+0(SB), Y3
	VMOVUPS pi_over_2<>+0(SB), Y4
	VMOVUPS pi<>+0(SB), Y5
	VMOVUPS sign_mask<>+0(SB), Y6

loop:
	CMPQ        BX, $0x08
	JL          tail
	VMOVUPS     (AX), Y7
	VMOVUPS     (CX), Y8
	VANDNPS     Y7, Y6, Y9
	VANDNPS     Y8, Y6, Y10
	VMINPS      Y10, Y9, Y11
	VMAXPS      Y10, Y9, Y12
	VDIVPS      Y12, Y11, Y11
	VMULPS      Y11, Y11, Y12
	VMOVUPS     Y3, Y13
	VFMADD213PS Y2, Y12, Y13
	VFMADD213PS Y1, Y12, Y13
	VFMADD213PS Y0, Y12, Y13
	VMULPS      Y11, Y12, Y12
	VFMADD213PS Y11, Y12, Y13
	VCMPPS      $0x0e, Y10, Y9, Y9
	VSUBPS      Y13, Y4, Y10
	VBLENDVPS   Y9, Y10, Y13, Y13
	VXORPS      Y9, Y9, Y9
	VCMPPS      $0x01, Y9, Y8, Y9
	VSUBPS      Y13, Y5, Y8
	VBLENDVPS   Y9, Y8, Y13, Y13
	VANDPS      Y7, Y6, Y7
	VXORPS      Y13, Y7, Y13
	VMOVUPS     Y13, (DX)
	ADDQ        $0x20, AX
	ADDQ        $0x20, CX
	ADDQ        $0x20, DX
	SUBQ        $0x08, BX
	JMP         loop

tail:
	CMPQ        BX, $0x00
	JE          done
	VMOVSS      (AX), X0
	VMOVSS      (CX), X1
	VMOVUPS     sign_mask<>+0(SB), X2
	VANDNPS     X0, X2, X3
	VANDNPS     X1, X2, X4
	VMINSS      X4, X3, X5
	VMAXSS      X4, X3, X6
	VDIVSS      X6, X5, X5
	VMULSS      X5, X5, X6
	VMOVSS      atan_c4<>+0(SB), X7
	VMOVSS      atan_c3<>+0(SB), X8
	VFMADD213SS X8, X6, X7
	VMOVSS      atan_c2<>+0(SB), X8
	VFMADD213SS X8, X6, X7
	VMOVSS      atan_c1<>+0(SB), X8
	VFMADD213SS X8, X6, X7
	VMULSS      X5, X6, X6
	VFMADD213SS X5, X6, X7
	VCMPSS      $0x0e, X4, X3, X3
	VMOVSS      pi_over_2<>+0(SB), X4
	VSUBSS      X7, X4, X4
	VBLENDVPS   X3, X4, X7, X7
	VXORPS      X3, X3, X3
	VCMPSS      $0x01, X3, X1, X3
	VMOVSS      pi<>+0(SB), X1
	VSUBSS      X7, X1, X1
	VBLENDVPS   X3, X1, X7, X7
	VANDPS      X0, X2, X0
	VXORPS      X7, X0, X7
	VMOVSS      X7, (DX)
	ADDQ        $0x04, AX
	ADDQ        $0x04, CX
	ADDQ        $0x04, DX
	DECQ        BX
	JMP         tail

done:
	VZEROUPPER
	RET

DATA atan_c1<>+0(SB)/4, $(-0.33333334)
DATA atan_c1<>+4(SB)/4, $(-0.33333334)
DATA atan_c1<>+8(SB)/4, $(-0.33333334)
DATA atan_c1<>+12(SB)/4, $(-0.33333334)
DATA atan_c1<>+16(SB)/4, $(-0.33333334)
DATA atan_c1<>+20(SB)/4, $(-0.33333334)
DATA atan_c1<>+24(SB)/4, $(-0.33333334)
DATA atan_c1<>+28(SB)/4, $(-0.33333334)
GLOBL atan_c1<>(SB), RODATA|NOPTR, $32

DATA atan_c2<>+0(SB)/4, $(0.2)
DATA atan_c2<>+4(SB)/4, $(0.2)
DATA atan_c2<>+8(SB)/4, $(0.2)
DATA atan_c2<>+12(SB)/4, $(0.2)
DATA atan_c2<>+16(SB)/4, $(0.2)
DATA atan_c2<>+20(SB)/4, $(0.2)
DATA atan_c2<>+24(SB)/4, $(0.2)
DATA atan_c2<>+28(SB)/4, $(0.2)
GLOBL atan_c2<>(SB), RODATA|NOPTR, $32

DATA atan_c3<>+0(SB)/4, $(-0.14285715)
DATA atan_c3<>+4(SB)/4, $(-0.14285715)
DATA atan_c3<>+8(SB)/4, $(-0.14285715)
DATA atan_c3<>+12(SB)/4, $(-0.14285715)
DATA atan_c3<>+16(SB)/4, $(-0.14285715)
DATA atan_c3<>+20(SB)/4, $(-0.14285715)
DATA atan_c3<>+24(SB)/4, $(-0.14285715)
DATA atan_c3<>+28(SB)/4, $(-0.14285715)
GLOBL atan_c3<>(SB), RODATA|NOPTR, $32

DATA atan_c4<>+0(SB)/4, $(0.11111111)
DATA atan_c4<>+4(SB)/4, $(0.11111111)
DATA atan_c4<>+8(SB)/4, $(0.11111111)
DATA atan_c4<>+12(SB)/4, $(0.11111111)
DATA atan_c4<>+16(SB)/4, $(0.11111111)
DATA atan_c4<>+20(SB)/4, $(0.11111111)
DATA atan_c4<>+24(SB)/4, $(0.11111111)
DATA atan_c4<>+28(SB)/4, $(0.11111111)
GLOBL atan_c4<>(SB), RODATA|NOPTR, $32

DATA pi_over_2<>+0(SB)/4, $(1.5707964)
DATA pi_over_2<>+4(SB)/4, $(1.5707964)
DATA pi_over_2<>+8(SB)/4, $(1.5707964)
DATA pi_over_2<>+12(SB)/4, $(1.5707964)
DATA pi_over_2<>+16(SB)/4, $(1.5707964)
DATA pi_over_2<>+20(SB)/4, $(1.5707964)
DATA pi_over_2<>+24(SB)/4, $(1.5707964)
DATA pi_over_2<>+28(SB)/4, $(1.5707964)
GLOBL pi_over_2<>(SB), RODATA|NOPTR, $32

DATA pi<>+0(SB)/4, $(3.1415927)
DATA pi<>+4(SB)/4, $(3.1415927)
DATA pi<>+8(SB)/4, $(3.1415927)
DATA pi<>+12(SB)/4, $(3.1415927)
DATA pi<>+16(SB)/4, $(3.1415927)
DATA pi<>+20(SB)/4, $(3.1415927)
DATA pi<>+24(SB)/4, $(3.1415927)
DATA pi<>+28(SB)/4, $(3.1415927)
GLOBL pi<>(SB), RODATA|NOPTR, $32

DATA sign_mask<>+0(SB)/4, $0x80000000
DATA sign_mask<>+4(SB)/4, $0x80000000
DATA sign_mask<>+8(SB)/4, $0x80000000
DATA sign_mask<>+12(SB)/4, $0x80000000
DATA sign_mask<>+16(SB)/4, $0x80000000
DATA sign_mask<>+20(SB)/4, $0x80000000
DATA sign_mask<>+24(SB)/4, $0x80000000
DATA sign_mask<>+28(SB)/4, $0x80000000
GLOBL sign_mask<>(SB), RODATA|NOPTR, $32
